// <auto-generated />
using System;
using ExpensesSystem.DAL.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpensesSystem.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpensesSystem.DAL.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseObjectId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseObjectId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpensesSystem.DAL.Models.ExpenseObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExpenseObjects");
                });

            modelBuilder.Entity("ExpensesSystem.DAL.Models.Object", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseObjectId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("ExpensesSystem.DAL.Models.Expense", b =>
                {
                    b.HasOne("ExpensesSystem.DAL.Models.ExpenseObject", null)
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseObjectId");
                });

            modelBuilder.Entity("ExpensesSystem.DAL.Models.Object", b =>
                {
                    b.HasOne("ExpensesSystem.DAL.Models.ExpenseObject", null)
                        .WithMany("Objects")
                        .HasForeignKey("ExpenseObjectId");
                });

            modelBuilder.Entity("ExpensesSystem.DAL.Models.ExpenseObject", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
